print("selam herkese ....\nnasılsınız\nbugün\nbakalım")
print("pyhton\töğrenmek\toldukça\tkolay")
print("pyhton\t\töğrenmek\t\toldukça\t\tkolay")
print("Ecodation Eğitim Kurumları İle \npyhton \tkursu")
print("\"Ecodation\" Eğitim Kurumları")
print('Türkiye\'nin Başkenti Ankara\'dır.')
print("1.öğrenci\t= \"Buse\"")
print("2.öğrenci\t= \"Ender\"")
print("3.öğrenci\t= \"Berk\"")