print("Ne", "Mutlu","Türk'üm","Diyene")
print("Mustafa","Kemal","Atatürk")
print("==================================")
print("Ne","Mutlu","Türk'üm","Diyene", end="\n")
print("Mustafa","Kemal","Atatürk")
print("==================================")
print("İstanbul","Artık","İyice", sep="-" , end=">>\n")
print("Çekilmez","Hal","Aldı", sep="*" , end=".")